### ISSUE TITLE
Support Java 11s new attributes and validate that the invoke instructions still work as expected

### ISSUE THREAD

**Issue by florian-kuebler** [stg-tud/opal-backup#20]
From Bitbucket#171:
>Basically add support for the new JEP for Java 11

**Comment by florian-kuebler** [comment]
Also see #19

**Comment by errt** [comment]
These are the relevant tasks that need to be performed in order to support Java 11+:
- [x] Support resolution of invokevirtual and invokeinterface instructions to private methods
- [x] Check whether changes are needed in regard to private methods and invokestatic
- [x] Check whether changes are needed to support resolution of invokespecial instructions to non-private methods
- [x] Support the NestHost and NestMembers attributes, including resolution of private members, including fields, by (at least) other classes from the same nest
- [x] Support the CONSTANT_Dynamic_info and its use in ldc, ldc_w, and ldc2_w bytecodes, including the bootstrap methods from java.lang.invoke.ConstantBootstraps

No further changes should be necessary to support Java 12-14.

For Java 15+:
- [x] Check that Java 15's move to the 2019 IEEE 754 floating point standard does not require any changes, in particular in abstract interpretation (checked that - it is only naming changes, single/double are now named binary32/64 in the standard and denormalized has been renamed to subnormal)

Note that this list does not include preview features that may also have an impact, such as Java 15's Records that introduce new classfile attributes. However, these features are not part of the official JVM specification.
